# Generated by Django 4.1.1 on 2023-11-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='user_id')),
                ('email', models.CharField(max_length=127, verbose_name='email')),
                ('user_name', models.CharField(max_length=10, verbose_name='user_name')),
                ('password', models.CharField(max_length=10, verbose_name='password')),
                ('avatar', models.IntegerField()),
            ],
            options={
                'verbose_name': 'user',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='post_id')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('content', models.TextField(verbose_name='text')),
                ('create_date', models.DateField(verbose_name='created_date')),
                ('user_id', models.ForeignKey(max_length=8, on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='user_poster_id')),
            ],
        ),
    ]
