# Generated by Django 4.1.1 on 2023-11-21 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='board_name')),
            ],
            options={
                'verbose_name': 'board',
                'db_table': 'board',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='', upload_to='images/')),
            ],
            options={
                'db_table': 'tb_images',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
                ('content', models.TextField(verbose_name='text')),
                ('create_date', models.DateField(verbose_name='created_date')),
                ('image', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.image', verbose_name='post_image')),
            ],
            options={
                'verbose_name': 'post',
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='tag_name')),
            ],
            options={
                'verbose_name': 'tag',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, verbose_name='user_name')),
                ('email', models.CharField(max_length=127, verbose_name='email')),
                ('password', models.CharField(max_length=10, verbose_name='password')),
                ('avatar', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.image', verbose_name='avatar')),
            ],
            options={
                'verbose_name': 'user',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.post', verbose_name='post')),
                ('tag', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.tag', verbose_name='tag')),
            ],
            options={
                'verbose_name': 'tag_post',
                'db_table': 'tags_post',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='user_poster_id'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='text')),
                ('res_comment', models.IntegerField(default=-1, verbose_name='res_to_comment_id')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.post', verbose_name='post_id')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='user_id')),
            ],
            options={
                'verbose_name': 'comment',
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.board', verbose_name='board')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'board_post',
                'db_table': 'board_post',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.post', verbose_name='post_id')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='user_id')),
            ],
            options={
                'verbose_name': 'like',
                'db_table': 'like',
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.comment', verbose_name='comment_id')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='user_id')),
            ],
            options={
                'verbose_name': 'like_comment',
                'db_table': 'likes_comment',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.post', verbose_name='post_id')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='user_id')),
            ],
            options={
                'verbose_name': 'collection',
                'db_table': 'collection',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
