# Generated by Django 4.1.1 on 2023-11-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ann',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('content', models.TextField(verbose_name='content')),
            ],
            options={
                'verbose_name': 'Ann',
                'db_table': 'tb_Ann',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(verbose_name='create_date')),
                ('content', models.TextField(verbose_name='content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='receiver')),
            ],
            options={
                'verbose_name': 'notice',
                'db_table': 'tb_Notice',
            },
        ),
    ]
