# Generated by Django 4.1.1 on 2023-12-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_ann_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=8, unique=True, verbose_name='tag_name'),
        ),
    ]
