# Generated by Django 4.1.1 on 2023-11-20 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_post_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_name',
        ),
    ]
