# Generated by Django 4.1.1 on 2023-11-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_post_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
