# Generated by Django 4.1.1 on 2023-11-20 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_rename_user_id_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.post', verbose_name='post_id')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.user', verbose_name='user_id')),
            ],
            options={
                'verbose_name': 'like',
                'db_table': 'like',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
