# Generated by Django 4.1.1 on 2023-12-05 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_boardpost_unique_together_alter_boardpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpost',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.post', verbose_name='post'),
        ),
    ]
