# Generated by Django 4.1.1 on 2023-12-05 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_boardpost_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagpost',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.post', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=8, verbose_name='tag_name'),
        ),
    ]
