# Generated by Django 4.1.1 on 2023-12-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_boardpost_post_alter_tag_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.image', verbose_name='image')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.post', verbose_name='post')),
            ],
            options={
                'db_table': 'post_image',
            },
        ),
    ]
