# Generated by Django 4.1.1 on 2023-12-11 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_post_image_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='isUnRead',
            field=models.BooleanField(default=True, verbose_name='isUnRead'),
        ),
        migrations.AddField(
            model_name='notice',
            name='related_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.post', verbose_name='related_post'),
        ),
    ]
